### ISSUE TITLE
UnknownError on Firefox Developer Edition 36.0a2 (2015-01-08)

### ISSUE THREAD

**Issue by basiclines** [mozilla/localForage#335]
When using a simple get/set item localforage throws an `UnknownError` and an exception `[object DOMError]`

Example code:
```js
localforage.setItem("foo", "yeah", function success(){
  console.log("set");
})
```

```js
localforage.getItem("foo", function success(error, key){
  console.log("get");
  console.log(error);
  console.log(key);
})
```
Firefox Stable logs perfectly the code above,
![Logging screenshot](https://pbs.twimg.com/media/B60-qbNIcAAjPps.png)

This has been tested by loading `localforage (1.2.1)` via `requirejs (2.1.15)`.

Hope it helps!

**Comment by godchuanz** [comment]
I'm facing the exact same issue, but I'm on Firefox 35 (Windows).
It worked fine on Firefox 34.0.5 (Windows).

Chrome and IE both worked fine, so it could be a Firefox issue rather than a Localforage issue. Either way, it's a Mozilla issue.

Anyone any ideas why this is happening?

**Comment by basiclines** [comment]
This is still happening in latest Firefox Developer builds.

**Comment by tofumatt** [comment]
Indeed, this is still on my radar but I'm currently moving countries and really swamped. If anyone else could check it out that would be excellent, if not I'll try to get to it ASAP.

**Comment by godchuanz** [comment]
If it helps, I realised that if all IndexedDB files are deleted manually from computer, the error doesn't occur. This suggests something in IndexedDB changed in Firefox v35 onwards, which is somehow incompatible with db files created in previous versions. I can't be sure though.

**Comment by tofumatt** [comment]
That’s strange, as the spec should be pretty well-implemented. I’ll file a bug and see what comes of it.

**Comment by tofumatt** [comment]
Oddly, I see "No available storage method found." when running:

```javascript
localforage.getItem("foo", function success(error, key){
  console.log("get");
  console.log(error);
  console.log(key);
})
```

in Developer Edition on Mac (`38.02a`). Still investigating, just wanted to log that here for posterity.

**Comment by scunliffe** [comment]
Looking at the error I see in Firefox 36.0.1 there's 2 keys in the error object, name=Unknown Error and message="The operation failed for reasons unrelated to the database itself and not covered by any other error code"

The same error code occurred years ago in this bugzilla report: https://bugzilla.mozilla.org/show_bug.cgi?id=643318 whereby Firefox wouldn't let the IndexedDB be created on the localhost.

This seems highly suspicious since that is exactly the same place I am currently trying to set it (as I would expect any developer to while developing).

Finally this great site: http://demo.agektmr.com/storage/ that lets you test the maximum limits of various local storage options shows Firefox as "not supporting" IndexedDB even though it *should* be supported: http://caniuse.com/#search=IndexedDB in Firefox 35+

Thus it looks like an underlying Firefox issue - but I can't seem to find a current bugzilla report for it. I'm going to see if I can create a simple test case that fails and if so file a bug with bugzilla.

**Comment by tofumatt** [comment]
Thanks, that'd be great. Feel free to cc me on the bug and link to it here.
I'm :tofumatt on Bugzilla too :-)

-tofumatt

**Comment by siddo420** [comment]
Having a similar issue in FF pvt window only.

I am on 39.0.3 Mac.

```
Localforage driver used: asyncStorage
Error: [object DOMError]
InvalidStateError
	
var openreq = indexedDB.open(dbInfo.name, dbInfo.version);    localforage.js (line 1154)
uncaught exception: [object DOMError]
```

asyncStorage works fine on regular (non-pvt) FF window.

**Comment by basiclines** [comment]
Hi @siddo420, Firefox does not allow to access to IndexedDB / Localstorage if the browser is in private mode. Otherwise Chromes allow it but does not keep the persistence.
You should check for `if (!!error && error.name == "InvalidStateError")  doSomething();` and provide an alternative fallback if needed?

Hope it helps!

**Comment by tofumatt** [comment]
Seems like this is a private browsing mode bug; closing.
