### ISSUE TITLE
Detecting minimal support for localForage

### ISSUE THREAD

**Issue by Rob-pw** [mozilla/localForage#336]
Will the following suffice in detecting whether localForage is usable in the current environment? My understanding is that localForage requires at least localStorage in order to function.

```javascript
return ('localStorage' in window && window.localStorage !== null);
```

Would a isSupported method on localForage be useful for quick detection? It might save adopters from implementing their own detection solutions, or resorting to potentially overkill solutions such as modernizr.

**Comment by tofumatt** [comment]
I don’t see an “isSupported” method being useful, especially as nearly any environment supports localStorage these days.

But checking the return value of localForage.driver() (which will return `null` if no driver is being used, which generally should only happen if you can’t use any drivers in the environment).

Are you having troubles with really old browsers breaking when you use localForage in an app?

**Comment by thgreasi** [comment]
We currently can use:
* [`localforage.driver() === null`](https://github.com/mozilla/localForage/blob/29f373e4fb8fa854a984b4e2e755212206beac0a/test/test.nodriver.js#L44) as @tofumatt  said
* [`localforage.supports(driverName)`](https://github.com/mozilla/localForage/blob/29f373e4fb8fa854a984b4e2e755212206beac0a/src/localforage.js#L377) which can be tested against the [driver name constants](https://github.com/mozilla/localForage/blob/29f373e4fb8fa854a984b4e2e755212206beac0a/test/test.nodriver.js#L11-L23).
* [`localforage.ready()` rejects with "No available storage method found"](https://github.com/mozilla/localForage/blob/29f373e4fb8fa854a984b4e2e755212206beac0a/test/test.nodriver.js#L26-L40)

**Comment by tofumatt** [comment]
Yeah, if none of these things even work then you're using a browser/environment that we just can't support, sorry :-/

**Comment by pghalliday** [comment]
Sorry for pinging an old issue, but it seems the place to record the answer to the question. I understand that in private browsing scenarios, localStorage will be available but won't actually store anything (https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API).

Does `localforage` detect this when determining what drivers are available?

**Comment by thgreasi** [comment]
[This](https://github.com/localForage/localForage/blob/master/src/utils/isLocalStorageValid.js) is what we are doing to detect localstorage support, in order to avoid data conflicts and reduce garbage in the storage. BUT, thankfully, in case that a browser is detected to have the localStorage API, but still can't save anything, then we fallback to the reject with a "no storage driver available" error.

If you need to have LF to look like it is saving data, even in those environments, then you can use the [memoryStorageDriver](https://github.com/localForage/localForage-memoryStorageDriver) and use it as the last argument in the `setDriver()` method.

**Comment by pghalliday** [comment]
That's great, thanks :)
