### ISSUE TITLE
Get rid of webSQL support

### ISSUE THREAD

**Issue by jgw96** [mozilla/localForage#349]
webSQL support should be deprecated in my opinion. It is an ancient form of web storage compared to something like indexedDB. With indexedDB support getting better everyday, and webSQL being slowly gotten rid of, support should be pulled. This could make localforage smaller, and give more focus to more modern types of web storage.

**Comment by thgreasi** [comment]
How about localStorage? Should it be dropped as well?
If yes, then should localForage be just a wrapper for indexeddb?

Since localforage supports even ie8, I don't think we should drop websql.
Otherwise, all safari users will have no other choice than using
localStorage and from any point of view websql is far better than the
blocking localstorage.

Gmail still uses websql so I don't think it's going away anytime soon (at
lest on the webkit/blink based browsers and this includes chrome, safari
and opera at the moment).

**Comment by tofumatt** [comment]
Sorry, WebSQL support is integral to localForage and dropping it would mean even current Safari versions wouldn't pass the tests without falling back to localStorage. We'll be keeping WebSQL support around for a while.
