### ISSUE TITLE
IndexedDB quota exceeded error during setItem doesn't not return an error to client

### ISSUE THREAD

**Issue by marcucio** [mozilla/localForage#359]
Tested on latest chrome web view on Android:

I am failing because of a quota exceeded error (rightfully so) but an error never gets returned. It looks like this code in setItem is being executed:
```
transaction.onabort = transaction.onerror = function() {
    reject(req.error);
};
 ```

but req.error is null. If that is null we should also check the transaction error. the function should actually be this:
```
transaction.onabort = transaction.onerror = function() {
     var err = req.error ? req.error : req.transaction.error;
     reject(err);
};
```

Also is localforage responsible for asking for more space on a quota exceeded error? Currently this is not happening.

Thanks

**Comment by marcucio** [comment]
Also I see for clear() + removeItem() we are just checking req error too not the transaction, maybe we should do the same for those?

**Comment by tofumatt** [comment]
Right now it doesn’t prompt for more space, for now I’d just recommend asking for a higher amount to begin with, but if it could be done I’d happy have it auto-prompt for more space!

Looks like we need to catch more errors, if you could submit a pull request that would be great, but otherwise we can get to it later.

-tofumatt

On 23 March 2015 at 15:48:13, Mike (notifications@github.com) wrote:

Tested on latest chrome web view on Android:

I am failing because of a quota exceeded error (rightfully so) but an error never gets returned. It looks like this code in setItem is being executed:

transaction.onabort = transaction.onerror = function() {
    reject(req.error);
};

but req.error is null. If that is null we should also check the transaction error. the function should actually be this:

transaction.onabort = transaction.onerror = function() {
     var err = req.error ? req.error : req.transaction.error;
     reject(err);
};

Also is localforage responsible for asking for more space on a quota exceeded error? Currently this is not happening.

Thanks

**Comment by marcucio** [comment]
Here is pull request for error checks:
https://github.com/mozilla/localForage/pull/360

 I'm going to look into increasing quota automatically, not sure yet if it should be done in the client or the localforage library

**Comment by tofumatt** [comment]
If it *can* be done in localForage I think that would be cool!

**Comment by af7** [comment]
I get the `QuotaExceededError` while I believe that I have an empty IndexedDB store, since I use store.clear() before I do a store.put(). I cannot use the DevTools to verify the store contents because I am working on an Android Fire TV environment. Why could this happen? Is the automatic increase in quota implemented?

**Comment by marcucio** [comment]
@af7 Not sure what is going on, Fire TV might not support IndexedDB right out of the box, you might have to use Cordova:

https://developer.amazon.com/public/solutions/platforms/cross-platform/cordova

> About the Amazon WebView API
> 
> By targeting the Amazon Fire OS platform, Cordova developers can create hybrid web apps that take advantage of the advanced web engine integrated into Fire devices.
> 
> Amazon WebView API (AWV) is a Chromium-derived web runtime exclusive to Fire OS. A drop-in replacement for the WebView that comes with Android devices, AWV makes it possible to create better performing and more powerful hybrid web apps by providing support for a faster JavaScript engine (V8), remote debugging, and hardware optimizations for Fire devices including an accelerated 2D Canvas, and access to HTML5 features not supported by Android’s built in WebView such as: CSS Calc, Form Validation, getUserMedia, IndexedDB, Web Workers, WebSockets and WebGL.
