### ISSUE TITLE
An InvalidStateError is throw in Firefox incognito

### ISSUE THREAD

**Issue by romainneutron** [mozilla/localForage#363]
This looks like #195, here the reproducer:

```
localforage.getItem('key', function (err, value) {
    console.log(err, value);
});
```

In case Firefox is opened in Incognito mode, an InvalidStateError is thrown.

**Comment by master-lincoln** [comment]
I can confirm this.

**Comment by vlkv** [comment]
Is there any workaround for this?

**Comment by tofumatt** [comment]
To my knowledge, no. Private browsing mode in several browsers make offline storage a lot buggier. You can file bugs with the right browsers, and I'll gladly add my support to them as important bugs to fix.




Sorry :-(



- tofumatt

**Comment by vlkv** [comment]
Well, we've created a fix this way:
var localForageDriver = [localforage.INDEXEDDB, localforage.LOCALSTORAGE, localforage.WEBSQL];
var localForageBackupDriver = [localforage.LOCALSTORAGE, localforage.WEBSQL, localforage.INDEXEDDB];

window.localForageReady = $.Deferred();

var configureLocalForage = function (localForageDriver) {
	var localForageOpts = {
	    driver: localForageDriver,
	};
	localforage.config(localForageOpts);
	window.localForageReady.resolve();
};

try {
	var idbConn = window.indexedDB.open("checkIndexedDB");
	idbConn.onerror = function (ex) {
		// We know for sure, that FF in private browsing mode restrict use of indexedDB. And indexedDB.open fails with InvalidStateError
		console.error("IndexedDB is NOT available");
		configureLocalForage(localForageBackupDriver);
	};
	idbConn.onsuccess = function (ex) {
		console.info("IndexedDB is available");
		configureLocalForage(localForageDriver);
	};
} catch (ex) {
	console.error("IndexedDB is NOT available, " + ex);
	configureLocalForage(localForageBackupDriver);
}

**Comment by tofumatt** [comment]
Interesting. What kind of results do you get doing something similar with Safari? I think it has similar errors with WebSQL and Private browsing mode.


- tofumatt

**Comment by thgreasi** [comment]
There is a chance that this could be handled inside `setDriver()` method.
We know only [check for browser support using some blocking tests](https://github.com/mozilla/localForage/blob/66ed3aeb261886c60f7805a1ccdbbb59d675eae0/src/localforage.js#L57-L84) and then try to setup the first supported driver, in priority order.
We could just try the next one each time setDriver fails until there is no driver left.

**Comment by tofumatt** [comment]
👍 That’s what I was thinking too.


- tofumatt

**Comment by thgreasi** [comment]
If we wait for ES7 we might be able to do something like:

```js
async function setDriver(driverNames) {
  for (var driverName of driverNames) {
    if (this.support(driverName) {
      try {
        let driver = await this.getDriver(driverName);
        if (driver) {
          return Promise.resolve(driver);
        }
      } catch (e) { }
    }
  }
  return Promise.reject('No supported driver found!');
}
```
:sparkles: :sparkles: :sparkles:

**Comment by tofumatt** [comment]
That is nice! Are there transpilers that support that now?



- tofumatt

**Comment by thgreasi** [comment]
[Babel with stage 1 experimental transformations enabled (proposal level)](https://babeljs.io/docs/usage/experimental/) can transpile it, but I'm not sure how elegant the generated code would be.

**Comment by thgreasi** [comment]
@tofumatt If we try to initialize the provided drivers inside setDriver,
then there are some considerations we should discuss.

* 1. "setDriver is called inside the constructor" VS "config() should be
called before initializing the driver". At the moment, we initialize the
driver inside the `ready()` call, the first time we use a localforage
method. (setDriver just fetches the driver object and sets its methods and
name.)
  * 1a. If we change that, to initialize the driver inside setDriver, in
order to detect supported drivers that fail to initialize, then we shorten
the time frame that is available to use config(). That's because setDriver
is also called inside the constructor.
  * 1b. A possible solution could be to do the full driver initialization
in setDriver but keep the driver initialization from the constructor lazy
(like in v1.2).
  * 1c. An other possible solution (thought that as I was writing this)
could be to store the driver preference array (eg: on the setDriver
promise) and do the initialization when ready() is called (like in v1.2 but
for the whole driver preference array).
* 2. There is a race condition on driver initialization when two subsequent
`localforage.setdriver('aDriver').then(localforage.ready)` are executed
with different driverNames as parameters. If we replace ready() with
getItem(), in the above example, then we can't be sure about the final
driver() in use (which driver will finish its initializaton last) and which
driver was used by each getItem(). There is also a case where the _dbInfo
holds different driver than the _driver property. This gets even worse if
we do the driver initialization inside the constructor, because we end up
with a code equivalent to the above example.
  * 2a. A way to work around this would be to wait for the previous driver
initialization to finish.

I've already a sample implementation for 1a and 2a but need further
feedback on this. Perhaps we could leave this for a later time (v1.4?)
after the webpack(?) bundling release.

On Fri, Aug 7, 2015, 22:09 Matthew Riley MacPherson <
notifications@github.com> wrote:

> That is nice! Are there transpilers that support that now?
>
>
>
> - tofumatt
>
> On Fri, Aug 7, 2015 at 7:39 PM, Thodoris Greasidis
> <notifications@github.com> wrote:
>
> > If we wait for ES7 we might be able to do something like:
> > ```js
> > async function setDriver(driverNames) {
> > for (var driverName of driverNames) {
> > if (this.support(driverName) {
> > try {
> > let driver = await this.getDriver(driverName);
> > if (driver) {
> > return Promise.resolve(driver);
> > }
> > } catch (e) { }
> > }
> > }
> > return Promise.reject('No supported driver found!');
> > }
> > ```
> > :sparkles: :sparkles: :sparkles:
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/mozilla/localForage/issues/363#issuecomment-128791368
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/363#issuecomment-128797680>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
@tofumatt Here is some code comparisons.

d6a92de3c8bcb176b9786f6f061ac9ba767c48d0 [source comparison](https://github.com/mozilla/localForage/compare/mozilla:master...thgreasi:d6a92de3c8bcb176b9786f6f061ac9ba767c48d0?expand=1)
This is like the above bullet `1a` and also takes care of `2`
* directly initializes the first supported driver
* fallbacks to the next one in case of error

[thgreasi:trysetdriver branch HEAD source comparison](https://github.com/mozilla/localForage/compare/mozilla:master...thgreasi:trysetdriver?expand=1)
This is like the above bullet `1c` and also takes care of `2`
* fetches and sets the driver as in v1.2
* lazily tries to initialize one of the supported drivers when `ready()` is called (probably through an other method) as in v1.2
* fallbacks to the next one in case of error inside the `ready()` promise

**Comment by tofumatt** [comment]
Looks like #448 should fix this one, but if not please let us know and reopen the issue.
