### ISSUE TITLE
Scoping problems when used with underscore.js

### ISSUE THREAD

**Issue by zrneely** [mozilla/localForage#408]
I have this line:

    return $.when.apply($, _.map(lfKeys, localForage.removeItem)).promise();

which is supposed to remove every item whose key is in the array `lfKeys` and return a promise for the removal of all of them. This needs to work in slightly older browsers, so I'm stuck using jQuery's promises (I'm not even sure if it's when function can handle es6/shimmed promises, but this was my experiment). The problem is that in the removeItem call, `this` is `window` . So as a result the `self.ready()` call throws an exception.

Wrapping the `localForage.removeItem` reference in an `_.bind(..., localForage)` call solves the problem (except that the callback is undefined, but that's a separate issue).

I'm not sure if this is an issue with the library, or if I'm violating the method's contract by calling it in this way, but I wanted to report it just in case.

**Comment by thgreasi** [comment]
Localforage supports more than one instances and `localforage` is just a
reference to the default auto-constructed instance. Some versions ago
`localforage` was a singleton not using an OO approach, so code like this
would probably work.
At the moment you need to make calls using the property notation so that a
proper `this` value is used (or use bind()).

You should be able to use:
$.when.apply($, _.map(lfKeys, function(k){ return
localforage.removeItem(k); })).promise();

Or:
$.when.apply($, _.map(lfKeys, localforage.removeItem,
localforage)).promise();

Or:

var removeItem = _.bind(localforage.removeItem, localforage);
$.when.apply($, _.map(lfKeys, removeItem)).promise();

PS: you can use Promise.all instead of $.when since I think that it is
polyfilled by localforage itself.

**Comment by tofumatt** [comment]
Yeah, looking at this I think it's works as expected, just need to use the code @thgreasi recommended.

If you still think it's a bug feel free to reopen with the exact code producing the error :smile:
