### ISSUE TITLE
Cordova/phonegap sqlite support

### ISSUE THREAD

**Issue by siddo420** [mozilla/localForage#411]
Has anyone tested this library with Cordova SQLite plugin (claims to be websql compatible with 1 exception)? Ref: https://github.com/litehelpers/Cordova-sqlite-storage

I found https://github.com/thgreasi/localForage-cordovaSQLiteDriver but not sure if it is supported as it is not listed in localForage's wiki.

Is it trivial to write my own localForage driver?

**Comment by thgreasi** [comment]
I hope you found your way around.
There is also a sample ionic app repo using it: https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp

**Comment by siddo420** [comment]
@thgreasi: thanks for the info and driver 

just wanted to ask if its being used in production or not and if it will work fine with https://github.com/mozilla/localForage-backbone or not.

**Comment by thgreasi** [comment]
@siddo420 I actually just implemented the driver as a proof of concept and for benchmarking purposes.
I have yet to use it on a prod level application, but I will probably ship one using it, in a month or two.
It should be working fine since:
* it uses [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) that is a proven high quality implementation
* in the "1000 parallel inserts & retrieves" benchmark in [localForage-cordovaSQLiteDriver-TestIonicApp](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp), it worked without any errors.
*  even though it's  a recent implementation, it already gets ~16 dls/month from npm (we don't know about bower stats) and I have yet to see any issue reported (which is a good sign)

Never used it with localForage-backbone and don't know the level that it supports custom drivers (I'm not actually a backbone person).
Hopefully, someone could give you better feedback than me.

**Comment by siddo420** [comment]
I am working with your driver now but for some reason I cannot find the location of sqlite db file on my device. I have confirmed the driver name used and also keys are being stored and retrieved without any issues.

I can see my app's directory under data/data/com.example.newapp but subfolders cache/ and files/ are empty.

What is the default database file name used and where is it stored?

**Comment by thgreasi** [comment]
The default database name should be "localforage" just like in the [websql driver](https://github.com/mozilla/localForage/tree/master/src/drivers).
Regarding the location of the db file, I really have no clue. You should refer to [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) docs.

Did you have any issues with the driver? Feel free to fill any issues in the driver's repo.
