### ISSUE TITLE
localForage won't save array - DOMException: Failed to execute 'put' on 'IDBObjectStore'

### ISSUE THREAD

**Issue by robcalcroft** [mozilla/localForage#533]
I have this code to update a state of my app:

```javascript
this.store.getItem('snapshots').then(snapshots => {
            let newSnapshots = [];

            snapshots.push(state);

            if (snapshots.length === 6) {
                newSnapshots = snapshots.slice(1, snapshots.length);
            } else {
                newSnapshots = snapshots;
            }

            this.store.setItem('snapshots', newSnapshots).catch(err => {
                console.log(err);
                if (err) {
                    throw new Error('Error whilst saving snapshot', err);
                }
            });
        });
```
And when I attempt to save the snapshot I get the following error in the catch: DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.(…)

**Comment by nolanlawson** [comment]
Is your `snapshots` object actually cloneable? One way you can check is to see if you can do `JSON.stringify(snapshots)`. If it contains circular references or custom classes or other fancy stuff, then IndexedDB cannot store it.

**Comment by robcalcroft** [comment]
Yep just ran `JSON.stringify(snapshots)` successfully. Length of the string was ~36K, is that too big for IndexedDB?

**Comment by nolanlawson** [comment]
Hm, well in that case it could be that it's still not cloneable. Are you sure that `JSON.parse(JSON.stringify(snapshots))` gives you exactly the same object back? Another way to test is to call a `postMessage()` on an iframe/webworker. I doubt it's because the object is too big.

What browser is this?

**Comment by robcalcroft** [comment]
Well running `_.isEqual(JSON.parse(JSON.stringify(snapshots)), snapshots);` returns `true`. Chrome 48

**Comment by robcalcroft** [comment]
Update: It fails the first time but then subsequent times it works with no issues :fearful:

**Comment by nolanlawson** [comment]
`_.isEqual(JSON.parse(JSON.stringify(snapshots)), snapshots);` might not be telling you the whole story. stringify might be removing stuff that IndexedDB cannot store (e.g. custom classes, functions).

If you could post a test to reproduce, that would be super helpful. :)

**Comment by robcalcroft** [comment]
That's gonna be tricky without stringifying the `state` which as you said might remove the problematic bit :confused:

**Comment by nolanlawson** [comment]
Yeah, that's probably exactly why it's not being stored in IndexedDB correctly. In general, you should only store JSON.stringifyable data in LocalForage. Even some slightly-tricky stuff that works in IndexedDB (like Dates) won't work in WebSQL and LocalStorage, so you may find that e.g. your tests pass in Chrome but are broken in Safari.

In general I'd say that unless your object is exactly the same when you do `JSON.parse(JSON.stringify(myObject))`, then don't store it in LocalForage (or any browser storage engine).

**Comment by robcalcroft** [comment]
The React state stuff is just raw data though and works fine because I'm already storing that data separately using forage.

**Comment by tofumatt** [comment]
I would try removing the React state (it's really not data)–I'd imagine there's some circular reference or something there that's affecting things.

Otherwise this might be a case where you need to stringify your data before saving it.

I'm going to close as array storage works but your data set doesn't; however if you find a fix to your issue let me know.

I have created #556 because of this though: maybe we can show developers better errors when they run into this issue. 👍
