### ISSUE TITLE
Cordova SQLite Plugin support

### ISSUE THREAD

**Issue by nolanlawson** [mozilla/localForage#550]
There is the [SQLite Plugin](https://github.com/litehelpers/Cordova-sqlite-storage) and also my [SQLite Plugin 2](https://github.com/nolanlawson/sqlite-plugin-2). Both of them are fairly API-compatible, and could be integrated into LocalForage's WebSQL adapter pretty easily.

Basically you'd just have to look for `window.sqlitePlugin.openDatabase` and prefer that to `window.openDatabase` if it's available. Also you may need to pass extra options through for SQLite Plugin 1 (see [PouchDB's approach](https://github.com/pouchdb/pouchdb/blob/999c19e1ebc246a18a5c378d4ffaf3673981ee00/src/adapters/websql/createOpenDBFunction-browser.js#L3-L18)), or if you just want to support SQLite Plugin 2, then it's fully compatible with the WebSQL API.

I think this would be a good issue for a first-timer, since it's nearly a one-line code change. I wouldn't recommend trying to test it, though, since you'd need Appium+device emulator or similar. Or as a test, you could just define a `sqlitePlugin.openDatabase` that routes to `window.openDatabase`.

**Comment by thgreasi** [comment]
After #538 gets merged, such a

**Comment by thgreasi** [comment]
After #538 gets merged, a slim custom driver for this implemented by just inheriting from the webSql driver and overriding the `_initStrorage` method. Already working on such approach for [localForage-cordovaSQLiteDriver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver).

**Comment by nolanlawson** [comment]
I still sorta feel like it would make the most sense to just modify the existing adapter to automatically use the SQLite Plugin. It's really a one-liner (you just check for `window.sqlitePlugin`; if it's not there, don't use it), and I think it would be a nice feature for Cordova users so that they could get up and running really easily with LocalForage without too much configuration.

**Comment by nolanlawson** [comment]
Hey, I just noticed that custom driver! Is there a difference between those two SQLite Plugin drivers - the one you wrote and the one by @Ecostack? In any case, it looks like that does indeed solve my issue, and either one of them would also be compatible with SQLite Plugin 2 (fwiw). I'll close this issue.

**Comment by thgreasi** [comment]
Those two plugins were developed and published independently but solve the same problem.
Initially the main difference was that my approach also waits for the `deviceready` event in case `sqlitePlugin` isn't yet there. Just yesterday I merged a PR that adds support for the `sqlitePlugin`v1.2 by using the [object parameter invocation overload for the `openDatabase()` method](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/blob/master/src/localforage-cordovasqlitedriver.js#L117-L123). An extra concern in the new version is that we also need to specify a `location` option for the database.
I will try using inheritance on the driver as found in #538. (I couldn't get this approach to work in the master branch since the used `serializer` is a closure referenced variable.)
Right after I will try using SQLite Plugin 2 and if everything works fine, I can add an extra note in README. Does it support the object notation invocation for the `openDatabase()` method?

**Comment by thgreasi** [comment]
Hi there again! This issue renewed my interest on the topic.
I'm experimenting with [a new branch that uses the `getSerializer()` and `getDriver()` methods](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/tree/inheritWebSqlDriver):
1) to retrieve the localforage webSql driver implementation and
2) override the _initStorage method
3) wire up the rest method to the webSql driver

My first working source code is just 2.08KB uncompressed (991 bytes gzipped)!

**Comment by nolanlawson** [comment]
> Does it support the object notation invocation for the openDatabase() method?

Yes it does, although it's much more lax than SQLite Plugin 1. All you need to do is pass in `{name:'myname'}`; any other options (such as `location`) are ignored.

**Comment by thgreasi** [comment]
Tried Cordova SQLite Plugin 2 and worked great :+1: 
Added a notice to the ["requirements" section of README](https://github.com/thgreasi/localForage-cordovaSQLiteDriver#requirements) and [created a branch on my test app repo](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/tree/cordova-plugin-sqlite-2)
