### ISSUE TITLE
Using localforage inside Firefox SDK Addons

### ISSUE THREAD

**Issue by duzun** [mozilla/localForage#584]
I intend to use localforage inside a Firefox SDK Addon, but it can't find any available storage.

IndexedDB is available though the API:

```js
var { indexedDB } = require('sdk/indexed-db');
```

But it can't be injected in module's global scope.

Is there any possibility to use localforage inside a Firefox Addon?

**Comment by tofumatt** [comment]
localForage should be able to be used inside a regular add-on, but because
Firefox is moving away from SDK add-ons and toward WebExtensions, sadly we
won’t be looking to fix this as it’s soon-to-be-deprecated technology.
Sorry!

**Comment by duzun** [comment]
Ok, I managed to use it inside an addon, with few changes though.
In the case someone else needs this, here are the changes:

1. Use PR #586;
2. Add this code to the top of `dist/localforage.js`:

```js
/**
 * Detect Firefox SDK Addon environment and prepare some globals
 *
 * @author Dumitru Uzun (DUzun.Me)
 */
(function (window, undefined) {
    if (typeof exports != "object" || typeof module == "undefined") return;

    if ( window && window.Array === Array ) try {
        // window is the sandbox global object
        window.window = window;

        // IndexedDB
        expo(require('sdk/indexed-db'));

        // Timers
        if ( typeof setTimeout == 'undefined' ) {
            expo(
                require("sdk/timers")
              , [
                    'setTimeout'  , 'clearTimeout',
                    'setImmediate', 'clearImmediate'
                ]
            );
        }

        // Hack to try and get some globals that are missing ffrom sandboxed global space
        // Blob, FileReader
        var Cu = require("chrome").Cu;
        var Services = Cu['import']("resource://gre/modules/Services.jsm", {});
        expo(
            Services
          , ['Blob', 'FileReader']
        );
        expo(
            Services.appShell && Services.appShell.hiddenDOMWindow
          , ['Blob', 'FileReader']
        );

    } catch(err) {
        // console.log('error', err);
    }

    function expo(ctx, props) {
        if ( !ctx ) return;
        if ( !props ) props = Object.keys(ctx);
        for(var i=props.length,p; i--;) {
            p = props[i];
            if ( ctx[p] != undefined && !(p in window) ) {
              window[p] = ctx[p];
            }
        }
        return ctx;
    }
}(this));

```

**Comment by thgreasi** [comment]
@duzun That's great!
How about creating a separate repo with this code, describing that it should be included before localforage???
@duzun @tofumatt It might also be a good idea to host it under [localForage-extensions](https://github.com/localForage-extensions) or [localForage](https://github.com/localForage).

**Comment by tofumatt** [comment]
Yeah I’ve been so busy but I think today I’ll move localForage itself into
the localForage group too.

I’ve also created a mailing list that I think will help us coordinate on
any new features, etc.:
https://groups.google.com/forum/#!forum/localforage Please
use it if people think it’s useful!

- tofumatt

On 3 July 2016 at 14:40:11, Thodoris Greasidis (notifications@github.com)
wrote:

@duzun <https://github.com/duzun> That's great!
How about creating a separate repo with this code, describing that it
should be included before localforage???
@duzun <https://github.com/duzun> @tofumatt <https://github.com/tofumatt>
It might also be a good idea to host it under localForage-extensions
<https://github.com/localForage-extensions> or localForage
<https://github.com/localForage>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/localForage/issues/584#issuecomment-230153977>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAFi9_mWaH-tNvu-dYhGw6a7daDMK1Zgks5qR7u7gaJpZM4JDtKq>
.

**Comment by thgreasi** [comment]
@tofumatt Great!
Please, give me a note which repos of the localForage-Extensions org should be moved there as well (probably all of them if you ask me - but just confirming anyway).

**Comment by tofumatt** [comment]
Yeah, moving all is a good idea. I’m gonna move the main one right now :-)

- tofumatt

On 3 July 2016 at 18:37:29, Thodoris Greasidis (notifications@github.com)
wrote:

@tofumatt <https://github.com/tofumatt> Great!
Please, give me a note which repos of the localForage-Extensions org should
be moved there as well (probably all of them if you ask me - but just
confirming anyway).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/localForage/issues/584#issuecomment-230165238>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAFi9-xABe1s6_Kx0_fqxuPgRvZzYtPTks5qR_NZgaJpZM4JDtKq>
.

**Comment by tofumatt** [comment]
Update: transferred! 😄

**Comment by duzun** [comment]
@thgreasi I like the idea of extension, but I don't see a way to bundle it in a separate file.
In Firefox SDK Addons each module has its own sandboxed environment, so the code above has to be in  the same file with indexedDB stuff, cause it adds some required globals to the current sandbox.
