### ISSUE TITLE
Store extremely large files

### ISSUE THREAD

**Issue by gmarty** [mozilla/localForage#69]
Hi,

I'm looking for a way to store huge files (possibly > 1 Go) on the browser. I had a look at the [FileSystem API](http://www.html5rocks.com/en/tutorials/file/filesystem/) (implemented in Chrome) and [FileHandle API](https://developer.mozilla.org/en-US/docs/WebAPI/FileHandle) (implemented in Firefox). Though both these APIs have very similar goals, there is no polyfill to unify their usage.

Is storing big files in the scope of LocalForage? If so, I'd love to help working on drivers for these. As a bonus, you'd get a nice quota manager (see #31) and blob storage (#28, #30, #40) for free!

**Comment by michielbdejong** [comment]
> so I can store data and files

Intuitively I sort of understand this distinction, but I'm having some trouble making it concrete. Is it fair to say we think of files as data that is "probably binary" and "probably big"? That seems to match the remark in the 22113e9 commit message:

> This partially addresses #69, as it allows for Blob storage, but doesn't
> address the issue of extremely large files, which neither localStorage nor
> WebSQL will support (their limits are too low).

Now that binary data is supported by all backends, I still see a use case for a filesystem backend.

I might some day try to build a custom backend that writes straight to the raw file system (using the key as the filename and the value as the file contents), so that I can use the sd-card on FxOS when available, and fall back to IndexedDB in other environments. Would have to work out how to deal with non-Blobs and key enumeration. But I would expect it to be faster than the IndexedDB backend for some use cases (it would bypass all of IndexedDB's unused complexity).

**Comment by tofumatt** [comment]
Using the actual file APIs seems unlikely inside localForage right now, though a driver could do it I suppose.

I'm going to close this as we do have Blob support and support binary storage. The specific large file case might even be covered by that.
